# -*- coding: utf-8 -*-
"""cleaning_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bhxXnXp73zI_xSlV28C0Tkeg9eKGdWq

Load the data and display the first 5 rows
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def load_data(path):
    return pd.read_csv(path)

def show_head(df):
    return df.head(5)

"""Check the shape of the dataset"""

def get_shape(df):
    return df.shape

"""Inspect data types and fix wrong types"""

def get_info(df):
    df.info()

def fix_data_types(df):
    df["MS SubClass"] = df["MS SubClass"].astype(str)
    df["Neighborhood"] = df["Neighborhood"].astype(str).str.lower().str.strip()
    return df

"""Find missing values

I handled the missing values differently depending on the type of column:


* For numeric columns, I filled the
missing values with the median to avoid the effect of outliers.

* For categorical columns, I filled the missing values with "Unknown" to keep all rows and indicate which values were missing.  List item.

"""

def handle_missing_values(df):

    numeric_cols = df.select_dtypes(include=np.number).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

    categorical_cols = df.select_dtypes(include="object").columns
    df[categorical_cols] = df[categorical_cols].fillna("Unknown")

    return df

"""Handle duplicates"""

def remove_duplicates(df):
    duplicates_count = df[df.duplicated()].shape[0]
    print(f"Found {duplicates_count} duplicate rows.")
    df_cleaned = df.drop_duplicates(ignore_index=True)
    return df_cleaned

"""Spot outliers"""

import matplotlib.pyplot as plt

def plot_boxplot(df):
    df["SalePrice"].plot.box()
    plt.title("Boxplot of SalePrice")
    plt.show()

plot_boxplot(cleaned_df)

def handle_outliers(df):
    if "SalePrice" in df.columns:
        upper_limit = df["SalePrice"].quantile(0.99)
        df["SalePrice"] = df["SalePrice"].clip(upper=upper_limit)
    return df

"""data cleaning and validation function

"""

df = load_data("/kaggle/input/ames-housing-dataset/AmesHousing.csv")
show_head(df)

def clean_data(path):
    df = load_data(path)
    show_head(df)

    print("Shape before cleaning:", df.shape)

    df = fix_data_types(df)
    df = handle_missing_values(df)
    df = remove_duplicates(df)
    df = handle_outliers(df)

    print("Shape after cleaning:", df.shape)

    assert df.isnull().sum().sum() == 0
    assert df.duplicated().sum() == 0
    assert (df["SalePrice"] > 0).all()

    return df

cleaned_df = clean_data("/kaggle/input/ames-housing-dataset/AmesHousing.csv")