# -*- coding: utf-8 -*-
"""eda_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-LrdbiSweey-wFxZxKAZITqQWlrjcMg
"""

from cleaning_01 import clean_data

"""Imports and Setup"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

df_phase1 = clean_data(dataset_path)

"""Histograms / KDE

We plotted the distribution of SalePrice, Gr Liv Area, and Overall Qual using histograms and KDE.
The plots show whether the distribution is skewed or approximately symmetric.
We can observe that most values cluster around the mean, while some extreme values represent outliers that could influence statistical analysis.
"""

def plot_histograms(df, features=["SalePrice", "Gr Liv Area", "Overall Qual"]):
    for col in features:
        plt.figure(figsize=(6,4))
        sns.histplot(df[col], kde=True)
        plt.title(f"Distribution of {col}")
        plt.show()
        skew = df[col].skew()
        mean = df[col].mean()
        print(f"{col} - Skew: {skew:.2f}, Mean: {mean:.2f}")
        if skew > 1:
            shape = "right-skewed"
        elif skew < -1:
            shape = "left-skewed"
        else:
            shape = "approximately symmetric"
        print(f"Insight: The distribution of {col} is {shape}, which suggests that most houses have {col.lower()} around the mean ({mean:.2f}). Outliers may exist on the extremes.\n")

"""Grouped Boxplots

We compared SalePrice across at least two categories for each feature, such as Bldg Type and House Style.
The results show which category has the highest and lowest average price.
This analysis demonstrates that building type and house style significantly affect the price, and visual comparison helps in identifying these differences clearly.
"""

def grouped_boxplot_with_insight(df, cat_cols=["Bldg Type", "House Style"], target="SalePrice"):
    insights = {}
    for cat_col in cat_cols:
        plt.figure(figsize=(8,5))
        sns.boxplot(x=cat_col, y=target, data=df)
        plt.title(f"{target} by {cat_col}")
        plt.xlabel(cat_col)
        plt.ylabel(target)
        plt.show()

        summary = df.groupby(cat_col)[target].mean().sort_values(ascending=False)
        print(f"Mean {target} by {cat_col}:\n{summary}")

        highest_group = summary.index[0]
        lowest_group = summary.index[-1]
        insight = (f"Observation: The {highest_group} category has the highest average {target} "
                   f"while the {lowest_group} category has the lowest average {target}. "
                   "This indicates that the type/style of house significantly impacts the price.")
        print("Insight:", insight, "\n")

        insights[cat_col] = insight

    return insights

"""Correlation Heatmap

We identified the top 10 features most correlated with SalePrice and visualized them in a heatmap.
This analysis helps determine which variables have the strongest influence on the price.
From the plot, we can see that features like Gr Liv Area and Overall Qual have a major impact on house value.

Scatter Plot
"""

def correlation_heatmap(df, target="SalePrice", top_n=10):
    import numpy as np
    import seaborn as sns
    import matplotlib.pyplot as plt

    numeric_df = df.select_dtypes(include=np.number)

    corr_matrix = numeric_df.corr()


    if target in corr_matrix.columns:
        top_corr = corr_matrix[target].abs().sort_values(ascending=False).head(top_n+1)

        top_features = top_corr.index
        top_corr_matrix = corr_matrix.loc[top_features, top_features]

        plt.figure(figsize=(8,6))
        sns.heatmap(top_corr_matrix, annot=True, cmap="coolwarm")
        plt.title(f"Top {top_n} Features Correlated with {target}")
        plt.show()

        print(f"Insight: The most correlated features with {target} are "
              f"{', '.join(top_features[1:])}. "
              "These features likely have strong influence on the target.\n")

    else:
        print(f"Target '{target}' is not numeric, cannot compute correlations.\n")

"""
This plot shows the relationship between SalePrice and Gr Liv Area, with color and size representing Overall Qual.
It is clear that larger houses tend to have higher prices, and higher quality further increases the price.
Visualizing multiple variables in this way allows us to understand complex relationships more easily."""

def scatter_plot(df, x="Gr Liv Area", y="SalePrice", hue="Overall Qual", size="Overall Qual"):
    plt.figure(figsize=(8,6))
    sns.scatterplot(x=x, y=y, hue=hue, size=size, data=df, palette="viridis", sizes=(20,200))
    plt.title(f"{y} vs {x} colored by {hue}")
    plt.show()

    print(f"Insight: There is a positive relationship between {x} and {y}. "
          f"Houses with higher {hue} tend to be larger and have higher prices, as indicated by color and size of the points.\n")

"""GroupBy Summary

We calculated the average SalePrice for each building type to identify the highest and lowest groups.
The results indicate that some building types have significantly higher prices than others.
This analysis highlights the influence of building type on price in a clear and quantitative manner.
"""

def groupby_summary(df, cat_col="Bldg Type", target="SalePrice"):
    summary = df.groupby(cat_col)[target].mean().sort_values(ascending=False)
    print("Mean target by category:\n", summary)

    highest_group = summary.index[0]
    lowest_group = summary.index[-1]
    print(f"\nHighest group: {highest_group} with mean {summary[0]:.2f}")
    print(f"Lowest group: {lowest_group} with mean {summary[-1]:.2f}\n")

    print(f"Insight: {highest_group} houses are most expensive on average, while {lowest_group} houses are least expensive. "
          "This confirms that building type strongly affects price.\n")
    return summary, highest_group, lowest_group

"""Manual Mean and Std

We manually calculated the mean and standard deviation of SalePrice without using pandas built-in functions.
This helps in understanding how basic statistics are computed step by step.
These values can be used later for normalization or comparing the variation in house prices.
"""

def manual_mean_std(y):
    y_array = np.array(y)
    mean = np.sum(y_array)/len(y_array)
    std = np.sqrt(np.sum((y_array - mean)**2)/len(y_array))
    print(f"Manual Mean: {mean:.2f}, Std: {std:.2f}")
    return mean, std

"""Standardize Column Manually

We standardized Gr Liv Area manually and calculated the Z-score for each value.
The results were compared with sklearn’s StandardScaler and matched perfectly.
This confirms that manual standardization is accurate and illustrates the process of data normalization.
"""

def standardize_column_manual(df, col):
    mean, std = manual_mean_std(df[col])
    z_manual = (df[col] - mean)/std
    print(f"First 5 manual standardized values:\n{z_manual.head()}")

    scaler = StandardScaler()
    z_sklearn = scaler.fit_transform(df[[col]]).flatten()
    print(f"First 5 sklearn standardized values:\n{z_sklearn[:5]}")

    comparison = np.allclose(z_manual, z_sklearn)
    print(f"\nDo manual Z and sklearn Z match? {comparison}\n")
    return z_manual, z_sklearn

"""Cosine Similarity

We measured the similarity between the highest and lowest SalePrice using cosine similarity.
This indicates how close or distant the numeric features are between the most expensive and least expensive houses.
It helps understand the variation in feature values across extreme price points.
"""

def cosine_high_low(df):
    numeric_df = df.select_dtypes(include=np.number)
    high_idx = df["SalePrice"].idxmax()
    low_idx = df["SalePrice"].idxmin()
    vec_high = numeric_df.loc[high_idx].values.reshape(1,-1)
    vec_low = numeric_df.loc[low_idx].values.reshape(1,-1)
    cos_sim = cosine_similarity(vec_high, vec_low)[0][0]
    print(f"Cosine similarity between highest and lowest SalePrice: {cos_sim:.2f}\n")
    return cos_sim

"""Estimate Probability

We estimated the fraction of high-quality houses (Overall Qual ≥7) that have SalePrice above 300,000.
The result shows that most high-quality houses are also high-priced, highlighting the impact of quality on price.
This quantitative analysis demonstrates the correlation between house quality and market value.
"""

def estimate_probability(df, quality_col="Overall Qual", threshold_price=300000, quality_threshold=7):
    high_quality = df[df[quality_col] >= quality_threshold]
    prob = (high_quality["SalePrice"] > threshold_price).mean()
    print(f"Fraction of high-quality items (Overall Qual >= {quality_threshold}) with SalePrice > {threshold_price}: {prob:.2f}")
    print(f"Insight: About {prob*100:.1f}% of high-quality houses are priced above ${threshold_price}. This shows high-quality homes tend to command higher prices.\n")
    return prob

def run_phase_3(dataset_path):
    df_phase1 = clean_data(dataset_path)

    print("=== Task 1: Histograms / KDE ===")
    plot_histograms(df_phase1)

    print("=== Task 2: Grouped Boxplots ===")
    grouped_boxplot_insight = grouped_boxplot_with_insight(df_phase1)

    print("=== Task 3: Correlation Heatmap ===")
    correlation_heatmap(df_phase1)

    print("=== Task 4: Scatter Plot ===")
    scatter_plot(df_phase1)

    print("=== Task 5: GroupBy Summary ===")
    groupby_summary(df_phase1)

    print("=== Task 6: Manual Mean and Std ===")
    manual_mean_std(df_phase1["SalePrice"])

    print("=== Task 7: Standardize Column Manually ===")
    standardize_column_manual(df_phase1, "Gr Liv Area")

    print("=== Task 8: Cosine Similarity ===")
    cosine_high_low(df_phase1)

    print("=== Task 9: Estimate Probability ===")
    estimate_probability(df_phase1)

dataset_path = "/kaggle/input/ames-housing-dataset/AmesHousing.csv"
run_phase_3(dataset_path)