# -*- coding: utf-8 -*-
"""feature_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iki5Uj13VqRNQtGQrgKFeG0_uFlygGXy
"""

from cleaning_01 import clean_data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

"""Categorical and Ordered Feature Encoding

“I used one-hot encoding for categorical columns and ordinal encoding for ordered columns to convert them into numerical features the model can understand and use.”
"""

def encode_features(df):
    df = pd.get_dummies(df, columns=["Neighborhood", "Bldg Type"], drop_first=True)

    quality_map = {"Po": 1, "Fa": 2, "TA": 3, "Gd": 4, "Ex": 5}
    if "Exter Qual" in df.columns:
        df["Exter Qual"] = df["Exter Qual"].map(quality_map)
    return df

"""Scaling Numerical Features

“I scaled numerical features using StandardScaler to make their values comparable and help the model learn faster. I fitted the scaler on the training data only to avoid data leakage.”
"""

def scale_features(df):
    X = df.drop("SalePrice", axis=1)
    y = df["SalePrice"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    scaler = StandardScaler()
    num_cols = X_train.select_dtypes(include=np.number).columns
    X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test[num_cols] = scaler.transform(X_test[num_cols])
    return X_train, X_test, y_train, y_test

"""Creating Domain Features (Safe Ratios)

“I created domain features like price_per_sqft and room_density to provide meaningful ratios that can help the model understand the relationships between price, area, and number of rooms. Using +1 ensures safe division and avoids errors from dividing by zero.”
"""

def create_domain_features(df):
    if "Gr Liv Area" in df.columns:
        df["price_per_sqft"] = df["SalePrice"] / (df["Gr Liv Area"] + 1)

    if "TotRms AbvGrd" in df.columns:
        df["room_density"] = df["TotRms AbvGrd"] / (df["Gr Liv Area"] + 1)
    return df

"""Creating Interaction Feature (Quality × Area)

“I created an interaction feature by multiplying quality and area to give the model extra information about how both together affect the price.”
"""

def create_interaction_feature(df):
    if "Gr Liv Area" in df.columns and "Overall Qual" in df.columns:
        df["quality_area"] = df["Gr Liv Area"] * df["Overall Qual"]
    return df

"""Log-Transform Skewed Feature (SalePrice)

“I applied a log transform to SalePrice to reduce skewness and make the data more normally distributed, which helps the model perform better. Histograms before and after show the improvement.”
"""

def log_transform(df):
    if "SalePrice" in df.columns:
        plt.hist(df["SalePrice"])
        plt.title("Before Log Transform")
        plt.show()

        df["SalePrice_log"] = np.log1p(df["SalePrice"])

        plt.hist(df["SalePrice_log"])
        plt.title("After Log Transform")
        plt.show()

    return df

"""Binning Column into Meaningful Groups (House Age)

“I binned the house age into meaningful groups to simplify the feature and help the model capture age-related patterns. One-hot encoding was applied to use these groups in the model.”
"""

def bin_column(df):
    if "Year Built" in df.columns:
        df["house_age"] = 2026 - df["Year Built"]
        bins = [0, 10, 30, 100, 200]
        labels = ["New", "Recent", "Old", "Very Old"]
        df["age_group"] = pd.cut(df["house_age"], bins=bins, labels=labels)

        df = pd.get_dummies(df, columns=["age_group"], drop_first=True)
    return df

"""Removing Redundant Features (High Correlation)

“I removed highly correlated features to avoid redundancy and multicollinearity, which helps the model learn more effectively and reduces overfitting.”
"""

def remove_high_correlation(df, threshold=0.95):
    corr_matrix = df.corr(numeric_only=True).abs()
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    to_drop = [column for column in upper.columns if any(upper[column] > threshold)]
    df = df.drop(columns=to_drop)
    print("Dropped columns:", to_drop)
    return df

"""Data Preparation Pipeline"""

def prepare_data_phase_two(df):
    df = encode_features(df)
    df = create_domain_features(df)
    df = create_interaction_feature(df)
    df = log_transform(df)
    df = bin_column(df)
    df = remove_high_correlation(df)
    return df

def full_pipeline(path):
    df = clean_data(path)
    df = prepare_data_phase_two(df)
    X_train, X_test, y_train, y_test = scale_features(df)
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = full_pipeline(
    "/kaggle/input/ames-housing-dataset/AmesHousing.csv")